services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  
  web:
    build: .
    container_name: fastapi_hw-web
    command: uvicorn app.app:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - redis
