name: Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Create .env file for Docker Compose
      run: |
        echo "POSTGRES_USER=ci_user" > .env
        echo "POSTGRES_PASSWORD=ci_password" >> .env
        echo "POSTGRES_DB=ci_db" >> .env
        echo "SECRET_KEY=${{ secrets.SECRET_KEY_CI }}" >> .env

    - name: Run tests with Docker Compose
      run: docker-compose -f docker-compose-test.yml up --build --abort-on-container-exit --exit-code-from web
        
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage.xml
        fail_ci_if_error: true